// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoutingServer.proto

package org.alps.rocky.core.proto;

public final class RoutingServer {
  private RoutingServer() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  /**
   * Protobuf enum {@code rocky.routing.OpsType}
   */
  public enum OpsType
          implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 修改
     * </pre>
     *
     * <code>Modify = 0;</code>
     */
    Modify(0),
    /**
     * <pre>
     * 停机
     * </pre>
     *
     * <code>Delete = 1;</code>
     */
    Delete(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 修改
     * </pre>
     *
     * <code>Modify = 0;</code>
     */
    public static final int Modify_VALUE = 0;
    /**
     * <pre>
     * 停机
     * </pre>
     *
     * <code>Delete = 1;</code>
     */
    public static final int Delete_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static OpsType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OpsType forNumber(int value) {
      switch (value) {
        case 0:
          return Modify;
        case 1:
          return Delete;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OpsType>
    internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            OpsType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OpsType>() {
              public OpsType findValueByNumber(int number) {
                return OpsType.forNumber(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return RoutingServer.getDescriptor().getEnumTypes().get(0);
    }

    private static final OpsType[] VALUES = values();

    public static OpsType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
                "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OpsType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rocky.routing.OpsType)
  }

  public interface InstanceInfoOrBuilder extends
          // @@protoc_insertion_point(interface_extends:rocky.routing.InstanceInfo)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 类型
     * </pre>
     *
     * <code>string profile = 1;</code>
     *
     * @return The profile.
     */
    String getProfile();

    /**
     * <pre>
     * 类型
     * </pre>
     *
     * <code>string profile = 1;</code>
     * @return The bytes for profile.
     */
    com.google.protobuf.ByteString
    getProfileBytes();

    /**
     * <code>string instanceId = 3;</code>
     *
     * @return The instanceId.
     */
    String getInstanceId();

    /**
     * <code>string instanceId = 3;</code>
     * @return The bytes for instanceId.
     */
    com.google.protobuf.ByteString
    getInstanceIdBytes();

    /**
     * <code>string ip = 4;</code>
     * @return The ip.
     */
    String getIp();

    /**
     * <code>string ip = 4;</code>
     *
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
    getIpBytes();

    /**
     * <code>int32 port = 5;</code>
     *
     * @return The port.
     */
    int getPort();

    /**
     * <code>bool active = 6;</code>
     *
     * @return The active.
     */
    boolean getActive();
  }

  /**
   * Protobuf type {@code rocky.routing.InstanceInfo}
   */
  public static final class InstanceInfo extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:rocky.routing.InstanceInfo)
          InstanceInfoOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use InstanceInfo.newBuilder() to construct.
    private InstanceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private InstanceInfo() {
      profile_ = "";
      instanceId_ = "";
      ip_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
      return new InstanceInfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return RoutingServer.internal_static_rocky_routing_InstanceInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return RoutingServer.internal_static_rocky_routing_InstanceInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      InstanceInfo.class, Builder.class);
    }

    public static final int PROFILE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object profile_ = "";

    /**
     * <pre>
     * 类型
     * </pre>
     *
     * <code>string profile = 1;</code>
     *
     * @return The profile.
     */
    @Override
    public String getProfile() {
      Object ref = profile_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        profile_ = s;
        return s;
      }
    }

    /**
     * <pre>
     * 类型
     * </pre>
     *
     * <code>string profile = 1;</code>
     *
     * @return The bytes for profile.
     */
    @Override
    public com.google.protobuf.ByteString
    getProfileBytes() {
      Object ref = profile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        profile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTANCEID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object instanceId_ = "";

    /**
     * <code>string instanceId = 3;</code>
     *
     * @return The instanceId.
     */
    @Override
    public String getInstanceId() {
      Object ref = instanceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        instanceId_ = s;
        return s;
      }
    }

    /**
     * <code>string instanceId = 3;</code>
     *
     * @return The bytes for instanceId.
     */
    @Override
    public com.google.protobuf.ByteString
    getInstanceIdBytes() {
      Object ref = instanceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        instanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object ip_ = "";

    /**
     * <code>string ip = 4;</code>
     *
     * @return The ip.
     */
    @Override
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }

    /**
     * <code>string ip = 4;</code>
     *
     * @return The bytes for ip.
     */
    @Override
    public com.google.protobuf.ByteString
    getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 5;
    private int port_ = 0;

    /**
     * <code>int32 port = 5;</code>
     *
     * @return The port.
     */
    @Override
    public int getPort() {
      return port_;
    }

    public static final int ACTIVE_FIELD_NUMBER = 6;
    private boolean active_ = false;

    /**
     * <code>bool active = 6;</code>
     * @return The active.
     */
    @Override
    public boolean getActive() {
      return active_;
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(profile_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, profile_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instanceId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, instanceId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(5, port_);
      }
      if (active_ != false) {
        output.writeBool(6, active_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(profile_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, profile_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instanceId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, instanceId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(5, port_);
      }
      if (active_ != false) {
        size += com.google.protobuf.CodedOutputStream
                .computeBoolSize(6, active_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof InstanceInfo)) {
        return super.equals(obj);
      }
      InstanceInfo other = (InstanceInfo) obj;

      if (!getProfile()
              .equals(other.getProfile())) return false;
      if (!getInstanceId()
              .equals(other.getInstanceId())) return false;
      if (!getIp()
              .equals(other.getIp())) return false;
      if (getPort()
              != other.getPort()) return false;
      if (getActive()
              != other.getActive()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getProfile().hashCode();
      hash = (37 * hash) + INSTANCEID_FIELD_NUMBER;
      hash = (53 * hash) + getInstanceId().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getActive());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InstanceInfo parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static InstanceInfo parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static InstanceInfo parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static InstanceInfo parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static InstanceInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static InstanceInfo parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static InstanceInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static InstanceInfo parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static InstanceInfo parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static InstanceInfo parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static InstanceInfo parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static InstanceInfo parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(InstanceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code rocky.routing.InstanceInfo}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:rocky.routing.InstanceInfo)
            InstanceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return RoutingServer.internal_static_rocky_routing_InstanceInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return RoutingServer.internal_static_rocky_routing_InstanceInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        InstanceInfo.class, Builder.class);
      }

      // Construct using org.alps.rocky.core.proto.RoutingServer.InstanceInfo.newBuilder()
      private Builder() {

      }

      private Builder(
              BuilderParent parent) {
        super(parent);

      }

      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        profile_ = "";
        instanceId_ = "";
        ip_ = "";
        port_ = 0;
        active_ = false;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return RoutingServer.internal_static_rocky_routing_InstanceInfo_descriptor;
      }

      @Override
      public InstanceInfo getDefaultInstanceForType() {
        return InstanceInfo.getDefaultInstance();
      }

      @Override
      public InstanceInfo build() {
        InstanceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public InstanceInfo buildPartial() {
        InstanceInfo result = new InstanceInfo(this);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartial0(InstanceInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.profile_ = profile_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.instanceId_ = instanceId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.ip_ = ip_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.port_ = port_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.active_ = active_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }

      @Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.setField(field, value);
      }

      @Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.addRepeatedField(field, value);
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InstanceInfo) {
          return mergeFrom((InstanceInfo) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InstanceInfo other) {
        if (other == InstanceInfo.getDefaultInstance()) return this;
        if (!other.getProfile().isEmpty()) {
          profile_ = other.profile_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getInstanceId().isEmpty()) {
          instanceId_ = other.instanceId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getActive() != false) {
          setActive(other.getActive());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                profile_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 26: {
                instanceId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 26
              case 34: {
                ip_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 34
              case 40: {
                port_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 40
              case 48: {
                active_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private Object profile_ = "";

      /**
       * <pre>
       * 类型
       * </pre>
       *
       * <code>string profile = 1;</code>
       *
       * @return The profile.
       */
      public String getProfile() {
        Object ref = profile_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          profile_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <pre>
       * 类型
       * </pre>
       *
       * <code>string profile = 1;</code>
       *
       * @return The bytes for profile.
       */
      public com.google.protobuf.ByteString
      getProfileBytes() {
        Object ref = profile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          profile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <pre>
       * 类型
       * </pre>
       *
       * <code>string profile = 1;</code>
       *
       * @param value The profile to set.
       * @return This builder for chaining.
       */
      public Builder setProfile(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        profile_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 类型
       * </pre>
       *
       * <code>string profile = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearProfile() {
        profile_ = getDefaultInstance().getProfile();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 类型
       * </pre>
       *
       * <code>string profile = 1;</code>
       *
       * @param value The bytes for profile to set.
       * @return This builder for chaining.
       */
      public Builder setProfileBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        profile_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object instanceId_ = "";

      /**
       * <code>string instanceId = 3;</code>
       *
       * @return The instanceId.
       */
      public String getInstanceId() {
        Object ref = instanceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          instanceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>string instanceId = 3;</code>
       *
       * @return The bytes for instanceId.
       */
      public com.google.protobuf.ByteString
      getInstanceIdBytes() {
        Object ref = instanceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          instanceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string instanceId = 3;</code>
       *
       * @param value The instanceId to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceId(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        instanceId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      /**
       * <code>string instanceId = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearInstanceId() {
        instanceId_ = getDefaultInstance().getInstanceId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      /**
       * <code>string instanceId = 3;</code>
       *
       * @param value The bytes for instanceId to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        instanceId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object ip_ = "";

      /**
       * <code>string ip = 4;</code>
       *
       * @return The ip.
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>string ip = 4;</code>
       *
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
      getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string ip = 4;</code>
       *
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ip_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      /**
       * <code>string ip = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        ip_ = getDefaultInstance().getIp();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      /**
       * <code>string ip = 4;</code>
       *
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        ip_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int port_;

      /**
       * <code>int32 port = 5;</code>
       *
       * @return The port.
       */
      @Override
      public int getPort() {
        return port_;
      }

      /**
       * <code>int32 port = 5;</code>
       *
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {

        port_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      /**
       * <code>int32 port = 5;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }

      private boolean active_;

      /**
       * <code>bool active = 6;</code>
       * @return The active.
       */
      @Override
      public boolean getActive() {
        return active_;
      }

      /**
       * <code>bool active = 6;</code>
       * @param value The active to set.
       * @return This builder for chaining.
       */
      public Builder setActive(boolean value) {

        active_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      /**
       * <code>bool active = 6;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearActive() {
        bitField0_ = (bitField0_ & ~0x00000010);
        active_ = false;
        onChanged();
        return this;
      }

      @Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rocky.routing.InstanceInfo)
    }

    // @@protoc_insertion_point(class_scope:rocky.routing.InstanceInfo)
    private static final InstanceInfo DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new InstanceInfo();
    }

    public static InstanceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstanceInfo>
            PARSER = new com.google.protobuf.AbstractParser<InstanceInfo>() {
      @Override
      public InstanceInfo parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InstanceInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InstanceInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public InstanceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ModuleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rocky.routing.ModuleInfo)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 命名空间
     * </pre>
     *
     * <code>string namespace = 1;</code>
     *
     * @return The namespace.
     */
    String getNamespace();

    /**
     * <pre>
     * 命名空间
     * </pre>
     *
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    com.google.protobuf.ByteString
    getNamespaceBytes();

    /**
     * <code>string moduleName = 2;</code>
     *
     * @return The moduleName.
     */
    String getModuleName();

    /**
     * <code>string moduleName = 2;</code>
     *
     * @return The bytes for moduleName.
     */
    com.google.protobuf.ByteString
    getModuleNameBytes();

    /**
     * <code>.rocky.routing.OpsType type = 3;</code>
     *
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();

    /**
     * <code>.rocky.routing.OpsType type = 3;</code>
     *
     * @return The type.
     */
    OpsType getType();

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    java.util.List<InstanceInfo>
    getInstancesList();

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    InstanceInfo getInstances(int index);

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    int getInstancesCount();

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    java.util.List<? extends InstanceInfoOrBuilder>
    getInstancesOrBuilderList();

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    InstanceInfoOrBuilder getInstancesOrBuilder(
            int index);
  }

  /**
   * <pre>
   * 模块信息
   * </pre>
   * <p>
   * Protobuf type {@code rocky.routing.ModuleInfo}
   */
  public static final class ModuleInfo extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:rocky.routing.ModuleInfo)
          ModuleInfoOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use ModuleInfo.newBuilder() to construct.
    private ModuleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private ModuleInfo() {
      namespace_ = "";
      moduleName_ = "";
      type_ = 0;
      instances_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
      return new ModuleInfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return RoutingServer.internal_static_rocky_routing_ModuleInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return RoutingServer.internal_static_rocky_routing_ModuleInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      ModuleInfo.class, Builder.class);
    }

    public static final int NAMESPACE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object namespace_ = "";

    /**
     * <pre>
     * 命名空间
     * </pre>
     *
     * <code>string namespace = 1;</code>
     *
     * @return The namespace.
     */
    @Override
    public String getNamespace() {
      Object ref = namespace_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }

    /**
     * <pre>
     * 命名空间
     * </pre>
     *
     * <code>string namespace = 1;</code>
     *
     * @return The bytes for namespace.
     */
    @Override
    public com.google.protobuf.ByteString
    getNamespaceBytes() {
      Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODULENAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object moduleName_ = "";

    /**
     * <code>string moduleName = 2;</code>
     *
     * @return The moduleName.
     */
    @Override
    public String getModuleName() {
      Object ref = moduleName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        moduleName_ = s;
        return s;
      }
    }

    /**
     * <code>string moduleName = 2;</code>
     *
     * @return The bytes for moduleName.
     */
    @Override
    public com.google.protobuf.ByteString
    getModuleNameBytes() {
      Object ref = moduleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        moduleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_ = 0;

    /**
     * <code>.rocky.routing.OpsType type = 3;</code>
     *
     * @return The enum numeric value on the wire for type.
     */
    @Override
    public int getTypeValue() {
      return type_;
    }

    /**
     * <code>.rocky.routing.OpsType type = 3;</code>
     *
     * @return The type.
     */
    @Override
    public OpsType getType() {
      OpsType result = OpsType.forNumber(type_);
      return result == null ? OpsType.UNRECOGNIZED : result;
    }

    public static final int INSTANCES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<InstanceInfo> instances_;

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    @Override
    public java.util.List<InstanceInfo> getInstancesList() {
      return instances_;
    }

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    @Override
    public java.util.List<? extends InstanceInfoOrBuilder>
    getInstancesOrBuilderList() {
      return instances_;
    }

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    @Override
    public int getInstancesCount() {
      return instances_.size();
    }

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    @Override
    public InstanceInfo getInstances(int index) {
      return instances_.get(index);
    }

    /**
     * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
     */
    @Override
    public InstanceInfoOrBuilder getInstancesOrBuilder(
            int index) {
      return instances_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(namespace_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespace_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moduleName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, moduleName_);
      }
      if (type_ != OpsType.Modify.getNumber()) {
        output.writeEnum(3, type_);
      }
      for (int i = 0; i < instances_.size(); i++) {
        output.writeMessage(4, instances_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(namespace_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespace_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moduleName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, moduleName_);
      }
      if (type_ != OpsType.Modify.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(3, type_);
      }
      for (int i = 0; i < instances_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(4, instances_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof ModuleInfo)) {
        return super.equals(obj);
      }
      ModuleInfo other = (ModuleInfo) obj;

      if (!getNamespace()
              .equals(other.getNamespace())) return false;
      if (!getModuleName()
              .equals(other.getModuleName())) return false;
      if (type_ != other.type_) return false;
      if (!getInstancesList()
              .equals(other.getInstancesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + MODULENAME_FIELD_NUMBER;
      hash = (53 * hash) + getModuleName().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getInstancesCount() > 0) {
        hash = (37 * hash) + INSTANCES_FIELD_NUMBER;
        hash = (53 * hash) + getInstancesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ModuleInfo parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ModuleInfo parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ModuleInfo parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ModuleInfo parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ModuleInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ModuleInfo parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ModuleInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static ModuleInfo parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ModuleInfo parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static ModuleInfo parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ModuleInfo parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static ModuleInfo parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ModuleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * 模块信息
     * </pre>
     * <p>
     * Protobuf type {@code rocky.routing.ModuleInfo}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:rocky.routing.ModuleInfo)
            ModuleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return RoutingServer.internal_static_rocky_routing_ModuleInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return RoutingServer.internal_static_rocky_routing_ModuleInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        ModuleInfo.class, Builder.class);
      }

      // Construct using org.alps.rocky.core.proto.RoutingServer.ModuleInfo.newBuilder()
      private Builder() {

      }

      private Builder(
              BuilderParent parent) {
        super(parent);

      }

      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        namespace_ = "";
        moduleName_ = "";
        type_ = 0;
        if (instancesBuilder_ == null) {
          instances_ = java.util.Collections.emptyList();
        } else {
          instances_ = null;
          instancesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return RoutingServer.internal_static_rocky_routing_ModuleInfo_descriptor;
      }

      @Override
      public ModuleInfo getDefaultInstanceForType() {
        return ModuleInfo.getDefaultInstance();
      }

      @Override
      public ModuleInfo build() {
        ModuleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ModuleInfo buildPartial() {
        ModuleInfo result = new ModuleInfo(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ModuleInfo result) {
        if (instancesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            instances_ = java.util.Collections.unmodifiableList(instances_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.instances_ = instances_;
        } else {
          result.instances_ = instancesBuilder_.build();
        }
      }

      private void buildPartial0(ModuleInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.namespace_ = namespace_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.moduleName_ = moduleName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }

      @Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.setField(field, value);
      }

      @Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.addRepeatedField(field, value);
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ModuleInfo) {
          return mergeFrom((ModuleInfo) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ModuleInfo other) {
        if (other == ModuleInfo.getDefaultInstance()) return this;
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getModuleName().isEmpty()) {
          moduleName_ = other.moduleName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (instancesBuilder_ == null) {
          if (!other.instances_.isEmpty()) {
            if (instances_.isEmpty()) {
              instances_ = other.instances_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureInstancesIsMutable();
              instances_.addAll(other.instances_);
            }
            onChanged();
          }
        } else {
          if (!other.instances_.isEmpty()) {
            if (instancesBuilder_.isEmpty()) {
              instancesBuilder_.dispose();
              instancesBuilder_ = null;
              instances_ = other.instances_;
              bitField0_ = (bitField0_ & ~0x00000008);
              instancesBuilder_ =
                      com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                              getInstancesFieldBuilder() : null;
            } else {
              instancesBuilder_.addAllMessages(other.instances_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                namespace_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                moduleName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                InstanceInfo m =
                        input.readMessage(
                                InstanceInfo.parser(),
                                extensionRegistry);
                if (instancesBuilder_ == null) {
                  ensureInstancesIsMutable();
                  instances_.add(m);
                } else {
                  instancesBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private Object namespace_ = "";

      /**
       * <pre>
       * 命名空间
       * </pre>
       *
       * <code>string namespace = 1;</code>
       *
       * @return The namespace.
       */
      public String getNamespace() {
        Object ref = namespace_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <pre>
       * 命名空间
       * </pre>
       *
       * <code>string namespace = 1;</code>
       *
       * @return The bytes for namespace.
       */
      public com.google.protobuf.ByteString
      getNamespaceBytes() {
        Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <pre>
       * 命名空间
       * </pre>
       *
       * <code>string namespace = 1;</code>
       *
       * @param value The namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespace(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        namespace_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 命名空间
       * </pre>
       *
       * <code>string namespace = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearNamespace() {
        namespace_ = getDefaultInstance().getNamespace();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 命名空间
       * </pre>
       *
       * <code>string namespace = 1;</code>
       *
       * @param value The bytes for namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespaceBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        namespace_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object moduleName_ = "";

      /**
       * <code>string moduleName = 2;</code>
       *
       * @return The moduleName.
       */
      public String getModuleName() {
        Object ref = moduleName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          moduleName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>string moduleName = 2;</code>
       *
       * @return The bytes for moduleName.
       */
      public com.google.protobuf.ByteString
      getModuleNameBytes() {
        Object ref = moduleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          moduleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string moduleName = 2;</code>
       *
       * @param value The moduleName to set.
       * @return This builder for chaining.
       */
      public Builder setModuleName(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        moduleName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      /**
       * <code>string moduleName = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearModuleName() {
        moduleName_ = getDefaultInstance().getModuleName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      /**
       * <code>string moduleName = 2;</code>
       *
       * @param value The bytes for moduleName to set.
       * @return This builder for chaining.
       */
      public Builder setModuleNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        moduleName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int type_ = 0;

      /**
       * <code>.rocky.routing.OpsType type = 3;</code>
       *
       * @return The enum numeric value on the wire for type.
       */
      @Override
      public int getTypeValue() {
        return type_;
      }

      /**
       * <code>.rocky.routing.OpsType type = 3;</code>
       *
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      /**
       * <code>.rocky.routing.OpsType type = 3;</code>
       *
       * @return The type.
       */
      @Override
      public OpsType getType() {
        OpsType result = OpsType.forNumber(type_);
        return result == null ? OpsType.UNRECOGNIZED : result;
      }

      /**
       * <code>.rocky.routing.OpsType type = 3;</code>
       *
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(OpsType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value.getNumber();
        onChanged();
        return this;
      }

      /**
       * <code>.rocky.routing.OpsType type = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<InstanceInfo> instances_ =
              java.util.Collections.emptyList();

      private void ensureInstancesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          instances_ = new java.util.ArrayList<InstanceInfo>(instances_);
          bitField0_ |= 0x00000008;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              InstanceInfo, InstanceInfo.Builder, InstanceInfoOrBuilder> instancesBuilder_;

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public java.util.List<InstanceInfo> getInstancesList() {
        if (instancesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instances_);
        } else {
          return instancesBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public int getInstancesCount() {
        if (instancesBuilder_ == null) {
          return instances_.size();
        } else {
          return instancesBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public InstanceInfo getInstances(int index) {
        if (instancesBuilder_ == null) {
          return instances_.get(index);
        } else {
          return instancesBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public Builder setInstances(
              int index, InstanceInfo value) {
        if (instancesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstancesIsMutable();
          instances_.set(index, value);
          onChanged();
        } else {
          instancesBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public Builder setInstances(
              int index, InstanceInfo.Builder builderForValue) {
        if (instancesBuilder_ == null) {
          ensureInstancesIsMutable();
          instances_.set(index, builderForValue.build());
          onChanged();
        } else {
          instancesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public Builder addInstances(InstanceInfo value) {
        if (instancesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstancesIsMutable();
          instances_.add(value);
          onChanged();
        } else {
          instancesBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public Builder addInstances(
              int index, InstanceInfo value) {
        if (instancesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstancesIsMutable();
          instances_.add(index, value);
          onChanged();
        } else {
          instancesBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public Builder addInstances(
              InstanceInfo.Builder builderForValue) {
        if (instancesBuilder_ == null) {
          ensureInstancesIsMutable();
          instances_.add(builderForValue.build());
          onChanged();
        } else {
          instancesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public Builder addInstances(
              int index, InstanceInfo.Builder builderForValue) {
        if (instancesBuilder_ == null) {
          ensureInstancesIsMutable();
          instances_.add(index, builderForValue.build());
          onChanged();
        } else {
          instancesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public Builder addAllInstances(
              Iterable<? extends InstanceInfo> values) {
        if (instancesBuilder_ == null) {
          ensureInstancesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, instances_);
          onChanged();
        } else {
          instancesBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public Builder clearInstances() {
        if (instancesBuilder_ == null) {
          instances_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          instancesBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public Builder removeInstances(int index) {
        if (instancesBuilder_ == null) {
          ensureInstancesIsMutable();
          instances_.remove(index);
          onChanged();
        } else {
          instancesBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public InstanceInfo.Builder getInstancesBuilder(
              int index) {
        return getInstancesFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public InstanceInfoOrBuilder getInstancesOrBuilder(
              int index) {
        if (instancesBuilder_ == null) {
          return instances_.get(index);
        } else {
          return instancesBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public java.util.List<? extends InstanceInfoOrBuilder>
      getInstancesOrBuilderList() {
        if (instancesBuilder_ != null) {
          return instancesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instances_);
        }
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public InstanceInfo.Builder addInstancesBuilder() {
        return getInstancesFieldBuilder().addBuilder(
                InstanceInfo.getDefaultInstance());
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public InstanceInfo.Builder addInstancesBuilder(
              int index) {
        return getInstancesFieldBuilder().addBuilder(
                index, InstanceInfo.getDefaultInstance());
      }

      /**
       * <code>repeated .rocky.routing.InstanceInfo instances = 4;</code>
       */
      public java.util.List<InstanceInfo.Builder>
      getInstancesBuilderList() {
        return getInstancesFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              InstanceInfo, InstanceInfo.Builder, InstanceInfoOrBuilder>
      getInstancesFieldBuilder() {
        if (instancesBuilder_ == null) {
          instancesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  InstanceInfo, InstanceInfo.Builder, InstanceInfoOrBuilder>(
                  instances_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          instances_ = null;
        }
        return instancesBuilder_;
      }

      @Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rocky.routing.ModuleInfo)
    }

    // @@protoc_insertion_point(class_scope:rocky.routing.ModuleInfo)
    private static final ModuleInfo DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new ModuleInfo();
    }

    public static ModuleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ModuleInfo>
            PARSER = new com.google.protobuf.AbstractParser<ModuleInfo>() {
      @Override
      public ModuleInfo parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ModuleInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ModuleInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public ModuleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_rocky_routing_InstanceInfo_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rocky_routing_InstanceInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rocky_routing_ModuleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rocky_routing_ModuleInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023RoutingServer.proto\022\rrocky.routing\032\023Ro" +
      "utingCommon.proto\"]\n\014InstanceInfo\022\017\n\007pro" +
      "file\030\001 \001(\t\022\022\n\ninstanceId\030\003 \001(\t\022\n\n\002ip\030\004 \001" +
      "(\t\022\014\n\004port\030\005 \001(\005\022\016\n\006active\030\006 \001(\010\"\211\001\n\nMod" +
      "uleInfo\022\021\n\tnamespace\030\001 \001(\t\022\022\n\nmoduleName" +
      "\030\002 \001(\t\022$\n\004type\030\003 \001(\0162\026.rocky.routing.Ops" +
      "Type\022.\n\tinstances\030\004 \003(\0132\033.rocky.routing." +
      "InstanceInfo*!\n\007OpsType\022\n\n\006Modify\020\000\022\n\n\006D" +
      "elete\020\001B*\n\031org.alps.rocky.core.protoB\rRo" +
      "utingServerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          RoutingCommon.getDescriptor(),
        });
    internal_static_rocky_routing_InstanceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rocky_routing_InstanceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rocky_routing_InstanceInfo_descriptor,
        new String[] { "Profile", "InstanceId", "Ip", "Port", "Active", });
    internal_static_rocky_routing_ModuleInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rocky_routing_ModuleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rocky_routing_ModuleInfo_descriptor,
        new String[] { "Namespace", "ModuleName", "Type", "Instances", });
    RoutingCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
